Repository LESSERAFIM-Aespa/TripMate, pull requests merged in 2023-11, with the labels that each got.

#161 Feat/searchpagerecommend
  app/src/main/java/kr/sparta/tripmate/api/naver/NaverNetWorkClient.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/ImageRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/search/ImageServerData.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/ImageRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ImageMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ImageServerDataEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/ImageRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetImageUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/ViewPager2Adapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/main/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/main/SearchScrollListener.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/main/SearchBlogFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/main/SearchBlogViewModel.kt
  app/src/main/res/drawable/search.png
  app/src/main/res/layout/fragment_scrap.xml
Labels: ⚙️ feat

#163 마이페이지 : 디자인수정
  app/src/main/res/drawable/mypage_baseline_create25.png
  app/src/main/res/drawable/mypage_menu_vertical.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🎨design

#165 마이페이지: 디자인 수정3
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🎨design

#166 탭 레이아웃 수정
  app/src/main/res/drawable/tablayout_indicator_shape.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: 🎨design

#168 Community&Home&Mypage 에러수정 및 UI 변경
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/community/FirebaseBoardRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/community/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/community/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/UpdateBoardUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/MyPageBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/MyPageScrapListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteViewModel.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_mypage_bookmark_item.xml
  app/src/main/res/values/colors.xml
Labels: ⚙️ feat, 🐛bug fix, 📚docs, 🎨design

#170 Community : 게시글 수정&추가 할 때 작성 조건 수정
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
Labels: 🐛bug fix

#171 Design/home
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/main/ScrapFragment.kt
  app/src/main/res/drawable/addimage.xml
  app/src/main/res/drawable/ic_app.png
  app/src/main/res/drawable/ic_app.xml
  app/src/main/res/drawable/scrap_content_outline.xml
  app/src/main/res/drawable/search.png
  app/src/main/res/drawable/search.xml
  app/src/main/res/font/bodonixt.ttf
  app/src/main/res/font/roboto_boldcondensed.ttf
  app/src/main/res/font/roboto_regular.ttf
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨design

#172 Design/home
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/styles.xml
Labels: 🎨design

#173 Design/home
  app/src/main/res/drawable/scrap_content_outline.xml
  app/src/main/res/layout/activity_scrap_detail.xml
  app/src/main/res/layout/activity_setting.xml
Labels: 🎨design

#175 Design/blog
  app/src/main/res/drawable/arrow_right.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/home_gridview_items.xml
  app/src/main/res/values/styles.xml
Labels: 🎨design

#176 가계부 디자인 변경
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/procedure/BudgetDetailProcedureFragment.kt
  app/src/main/res/drawable/background_budget_view_type5.xml
  app/src/main/res/drawable/shape_budget_detail_tab_bg.xml
  app/src/main/res/drawable/shape_budget_detail_tab_selected.xml
  app/src/main/res/layout/activity_budget_content.xml
  app/src/main/res/layout/activity_budget_detail.xml
  app/src/main/res/layout/activity_procedure_content.xml
  app/src/main/res/layout/activity_procedure_detail.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_budget_detail_procedure.xml
  app/src/main/res/layout/fragment_budget_detail_statistics.xml
  app/src/main/res/layout/item_budget.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_procedure.xml
  app/src/main/res/layout/itme_spinner.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ feat, 🎨design

#177 마이페이지: 디자인 수정 및 일부 기능 수정
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/res/drawable/share_button.png
  app/src/main/res/layout/fragment_my_page.xml
Labels: 📚docs, 🎨design

#179 Design/blog
  app/src/main/res/drawable/arrow_right.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: 🎨design

#181 마이페이지 : 활성화된 탭 반전효과 처리
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/res/drawable/budget2.png
  app/src/main/res/drawable/community2.png
  app/src/main/res/drawable/home2.png
  app/src/main/res/drawable/mypage2.png
  app/src/main/res/drawable/scrap2.png
  app/src/main/res/drawable/tablayout_indicator_shape.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🎨design

#184 <design> 홈화면 UI 수정
  app/src/main/res/layout/fragment_home.xml
Labels: 🎨design

#187 userpage&home&mypage&setting&community : UI, 버그, 기능 / github action 빌드 에러 후 수정 완료하고 재 빌드 완료했습니다.
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeBudgetListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/budget/HomeBudgetFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/budget/HomeBudgetViewModel.kt
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/homebudgetitem.xml
Labels: ⚙️ feat, 🐛bug fix, 📚docs, 🎨design

#191 가계부 버그 수정및 추가 개발
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/CategoryAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/main/BudgetDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/statistics/BudgetDetailStatisticsFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetContentViewModel.kt
  app/src/main/res/layout/activity_procedure_content.xml
  app/src/main/res/layout/activity_procedure_detail.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: ⚙️ feat, 🐛bug fix, 🎨design

#192 home&setting&community&userprofile : UI&버그&기능 수정
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/community/FirebaseBoardRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/community/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/community/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/GetBoardUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/MyPageBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/MyPageScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/detail/CommunityDetailFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/detail/CommunityDetailViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteViewModel.kt
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/homebudgetitem.xml
Labels: ⚙️ feat, 🐛bug fix, ♻️refactor, 🎨design

#194 community : 검색했을때 제목&내용에 검색어가 포함된 게시글만 화면에 보여줍니다.
  app/src/main/java/kr/sparta/tripmate/data/repository/community/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/community/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/GetBoardUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/UpdateBoardUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
Labels: ⚙️ feat

#202 홈 화면: 리펙토링
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/homebudgetitem.xml
  app/src/main/res/layout/scraptitems.xml
Labels: ♻️refactor, 🎨design

#204 Login& Setting : 로그인&회원탈퇴&로그아웃 기능
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/user/FirebaseUserRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/user/FirebaseUserRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/user/FirebaseUserRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseuserrepository/GetNickNameDataUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseuserrepository/LogoutUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/sharedpreferences/SharedPreferences.kt
Labels: ⚙️ feat

#207 기타 수정사항
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/user/FirebaseUserRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/MyPageScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/main/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/main/SearchBlogViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/sharedpreferences/SharedPreferences.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 🐛bug fix, ♻️refactor

#208 커뮤니티페이지: 탈퇴유저프로필 클릭 오류수정
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/user/FirebaseUserRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/user/FirebaseUserRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/user/FirebaseUserRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseuserrepository/GetUserDataUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/main/MyPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/userproflie/UserProfileViewModel.kt
Labels: 🐛bug fix

#210 약관추가
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/res/drawable/setting_button_terms.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🎨design

#212 가계부 과정 없을때 통계및 원금 남은금액 최신화 안되는 부분 수정
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/procedure/BudgetDetailProcedureFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/statistics/BudgetDetailStatisticsFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/budgetdetail/statistics/BudgetStatisticsFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/budgetdetail/statistics/BudgetStatisticsViewModel.kt
Labels: 🐛bug fix

#215 SharedPreference, object class 에서 data source로 변경및 usecase 추가
  app/src/main/java/kr/sparta/tripmate/data/datasource/local/budget/SharedPreferencesLocalDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/sharedpreference/SharedPreferenceReopositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/sharedpreference/SharedPreferenceReopository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/GetNickNameUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/GetProfileUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/GetUidFromUserUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/GetUidUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/RemoveKeyUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/SaveNickNameUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/SaveProfileUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/SaveUidFromUserUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/sharedpreference/SaveUidUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/MyPageBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/MyPageBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/MyPageScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/detail/ScrapDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/main/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/detail/CommunityDetailFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/detail/CommunityDetailViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/main/HomeFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/main/HomeViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/board/MyPageBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/board/MyPageBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/main/MyPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/main/MyPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/scrap/MyPageScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/scrap/MyPageScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/detail/ScrapDetailFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/detail/ScrapDetailViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/main/SearchBlogFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/main/SearchBlogViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/userproflie/UserProfileBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/userproflie/UserProfileBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/userproflie/UserProfileFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/userproflie/UserProfileViewModel.kt
Labels: ♻️refactor

#218 Login/Budget/Community/Main : UI&Bug&Feat
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/api/Constants.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/user/FirebaseUserRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/user/FirebaseUserRepository.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetcontent/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/statistics/BudgetDetailStatisticsFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/procedurecontent/ProcedureContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/splash/SplashActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_procedure_content.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_budget_detail_statistics.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🐛bug fix, 📚docs, 🎨design

#220 계정탈퇴시 가계부 모두삭제
  app/src/main/java/kr/sparta/tripmate/data/dao/BudgetDao.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/local/budget/BudgetLocalDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/budget/BudgetRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/budget/BudgetRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/budgetrepository/DeleteAllBudgetsUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/setting/SettingViewModel.kt
Labels: ⚙️ feat

#222 가계부 자잘한 오류 수정
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/procedure/BudgetDetailProcedureListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/budgetdetail/statistics/BudgetDetailStatisticsFragment.kt
Labels: ⚙️ feat

#223 1.0.4버전 : Login&splash&setting&budget&scrap : Bug, Feat, Ui를 수정 했습니다.
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/api/Constants.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/procedurecontent/ProcedureContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/splash/SplashActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/login/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/homebudgetitem.xml
  app/src/main/res/layout/scraptitems.xml
Labels: ⚙️ feat, 🐛bug fix, 🎨design

#224 Feat/main
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/splash/SplashActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/splash/SplashFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/splash/SplashViewModel.kt
Labels: 🐛bug fix
