Repository LESSERAFIM-Aespa/TripMate, pull requests merged in 2023-10, with the labels that each got.

#7 [feat]gourmet API
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/api/NaverNetWorkClient.kt
  app/src/main/java/kr/sparta/tripmate/api/NetWorkClient.kt
  app/src/main/java/kr/sparta/tripmate/api/NetWorkInterface.kt
  app/src/main/java/kr/sparta/tripmate/api/model/GourmetModel.kt
  app/src/main/java/kr/sparta/tripmate/api/serverdata/naver/GourmetServerData.kt
  app/src/main/java/kr/sparta/tripmate/fragment/gourmet/GourmetAdapter.kt
  app/src/main/java/kr/sparta/tripmate/fragment/gourmet/GourmetFragment.kt
  app/src/main/java/kr/sparta/tripmate/util/Constants.kt
  app/src/main/java/kr/sparta/tripmate/viewmodel/gourmet/GourmetFactory.kt
  app/src/main/java/kr/sparta/tripmate/viewmodel/gourmet/GourmetViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_gourmet.xml
  app/src/main/res/layout/gourmetitems.xml
Labels: ⚙️ feat, 🎨design

#22 UI/main
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/util/interface/ItemClick.kt
  app/src/main/res/drawable/titlebackground.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/gourmetitems.xml
  app/src/main/res/mipmap-hdpi/paintedstar.png
  app/src/main/res/mipmap-hdpi/star.png
  app/src/main/res/mipmap-mdpi/paintedstar.png
  app/src/main/res/mipmap-mdpi/star.png
  app/src/main/res/mipmap-xhdpi/paintedstar.png
  app/src/main/res/mipmap-xhdpi/star.png
  app/src/main/res/mipmap-xxhdpi/paintedstar.png
  app/src/main/res/mipmap-xxhdpi/star.png
  app/src/main/res/mipmap-xxxhdpi/paintedstar.png
  app/src/main/res/mipmap-xxxhdpi/star.png
  app/src/main/res/values/colors.xml
Labels: 🎨design

#27 Splash: 스플레시화면 구성완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/splash/SplashActivity.kt
  app/src/main/res/drawable/bg_splash.png
  app/src/main/res/drawable/ic_app.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: ⚙️ feat, 🎨design

#30 UI/login
  app/src/main/res/drawable/login_button_apple_outline.xml
  app/src/main/res/drawable/login_button_google_outline.xml
  app/src/main/res/drawable/loginapple.png
  app/src/main/res/drawable/logingoogle.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 🎨design

#32 mypage : xml 디자인 배치완료
  app/src/main/java/kr/sparta/tripmate/ui/main/ViewPager2Adapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/MyPageAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTab.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTabLayoutAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/ScrapBookmarkFragment.kt
  app/src/main/res/drawable/ic_setting.png
  app/src/main/res/drawable/mypage_button_cancel.xml
  app/src/main/res/drawable/mypage_button_submit.xml
  app/src/main/res/drawable/mypage_profile_box.xml
  app/src/main/res/drawable/mypage_profile_content_box.xml
  app/src/main/res/drawable/mypage_profile_content_box_edit.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_board.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_scrap_bookmark.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ feat, 🎨design

#35 Scrap : 화면출력오류 수정 및 MVVM 리펙토링
  app/src/main/java/kr/sparta/tripmate/api/naver/NaverNetWorkClient.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/ScrapRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/data/model/ScrapServerData.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapServerDataEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/ScrapRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetSearchBlogUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budgetmodel/BudgetFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budgetmodel/BudgetViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/communitymodel/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/communitymodel/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/HomeFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/homemodel/HomeFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/homemodel/HomeViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/MyPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/MyPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypagemodel/MyPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypagemodel/MyPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrapmodel/ScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrapmodel/ScrapViewModel.kt
  app/src/main/res/drawable/bg_splash.png
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🐛bug fix, ♻️refactor, 🎨design

#36 Community: 커뮤니티 Detail,Write 프래그먼트 파일추가
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetail.kt
  app/src/main/res/layout/fragment_community_detail.xml
Labels: 🆕new

#39 커뮤니티페이지:프래그먼트를 액티비티로 변경
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
Labels: 🆕new

#41 Design/community write
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/res/drawable/addimage.xml
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/drawable/ic_user_profile.png
  app/src/main/res/drawable/share.xml
  app/src/main/res/drawable/star.xml
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
Labels: 🎨design

#42 Login 기능 구현
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/domain/model/UserData.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/splash/SplashActivity.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: ⚙️ feat, 🐛bug fix, 🎨design

#47 scrap : GridView로 변경
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/res/drawable/blogimage.png
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/scraptitems.xml
Labels: 🎨design

#49 Feature/budget
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/data/dao/BudgetCategoriesDao.kt
  app/src/main/java/kr/sparta/tripmate/data/dao/BudgetDao.kt
  app/src/main/java/kr/sparta/tripmate/data/dao/CategoryDao.kt
  app/src/main/java/kr/sparta/tripmate/data/dao/CategoryProceduresDao.kt
  app/src/main/java/kr/sparta/tripmate/data/dao/ProcedureDao.kt
  app/src/main/java/kr/sparta/tripmate/data/model/budget/Budget.kt
  app/src/main/java/kr/sparta/tripmate/data/model/budget/BudgetCategories.kt
  app/src/main/java/kr/sparta/tripmate/data/model/budget/Category.kt
  app/src/main/java/kr/sparta/tripmate/data/model/budget/CategoryProcedures.kt
  app/src/main/java/kr/sparta/tripmate/data/model/budget/Procedure.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/BudgetRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/room/BudgetDatabase.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/BudgetRepository.kt
  build.gradle.kts
Labels: ⚙️ feat

#53 community main페이지: 디자인 완료
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_main_item.xml
  app/src/main/res/values/strings.xml
Labels: 🎨design

#56 CommunityMain : Recyclerview 적용완료
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/ViewPager2Adapter.kt
  app/src/main/res/layout/fragment_community.xml
Labels: ⚙️ feat

#60 scrap: firebase에 데이터 저장&삭제
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/sharedpreferences/SharedPreferences.kt
  app/src/main/res/drawable/love.png
  app/src/main/res/drawable/paintedlove.png
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/scraptitems.xml
Labels: ⚙️ feat, 🎨design

#64 setting : 로그아웃&회원탈퇴 기능 구현
  app/src/main/java/kr/sparta/tripmate/ui/setting/SettingActivity.kt
Labels: ⚙️ feat

#65 Home : UI
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/TabLayoutListener.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/sharedpreferences/SharedPreferences.kt
  app/src/main/res/drawable/rightarrow.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🎨design

#68 scrap : firebase 저장
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
Labels: ⚙️ feat, 🐛bug fix

#69 Budget : xml 디자인 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetDetailStatusFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureDetailActivity.kt
  app/src/main/res/drawable/arrow_left.xml
  app/src/main/res/drawable/background_budget_view_type1.xml
  app/src/main/res/drawable/background_budget_view_type2.xml
  app/src/main/res/drawable/background_budget_view_type3.xml
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_delete.png
  app/src/main/res/drawable/ic_edit.png
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/drawable/switch_track.xml
  app/src/main/res/font/inter.ttf
  app/src/main/res/layout/activity_budget_content.xml
  app/src/main/res/layout/activity_budget_detail.xml
  app/src/main/res/layout/activity_procedure_content.xml
  app/src/main/res/layout/activity_procedure_detail.xml
  app/src/main/res/layout/fragment_budget.xml
  app/src/main/res/layout/fragment_budget_detail_status.xml
  app/src/main/res/layout/item_budget.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_predure.xml
  app/src/main/res/layout/item_procedure_time.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨design

#70 커뮤니티 게시판에서 글 작성시 리싸이클러뷰에 표시 되게 구현
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_community.xml
Labels: ⚙️ feat

#71 커뮤니티 작성페이지 버그수정
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/res/layout/activity_community_write.xml
Labels: 🐛bug fix

#72 커뮤니티 글쓰기페이지: 버튼id 수정
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
Labels: 🐛bug fix

#74 home 기능 구현
  app/src/main/java/kr/sparta/tripmate/api/Constants.kt
  app/src/main/java/kr/sparta/tripmate/data/model/home/HomeScrapData.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/home/HomeFirstRepositorylmpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/UserData.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFirstAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/FirstViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/HomeFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/HomeViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/res/layout/empty_view.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_first_items.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🎨design, 💥hotfix

#76 mypage 북마크 기능
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
Labels: ⚙️ feat

#78 Feat/communitymain
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/res/layout/fragment_community.xml
Labels: ⚙️ feat

#80 커뮤니티 : 리소스파일 누락 수정, 겹친코드 수정
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/res/drawable/baseline_create_24.xml
  app/src/main/res/layout/fragment_community.xml
Labels: 🐛bug fix

#82 에러 수정 및 리펙토링
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/ScrapRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/scrap/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/data/model/scrap/ScrapServerData.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/ScrapRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/home/HomeFirstRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/ScrapModel.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/login/UserData.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ScrapMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ScrapServerDataEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/ScrapRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetSearchBlogUseCase.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFirstAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/FirstViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
Labels: 🐛bug fix, ♻️refactor

#83 커뮤니티 : 다른사람이 작성한 글이 표시되지않던 문제 수정
  app/src/main/java/kr/sparta/tripmate/data/repository/home/HomeFirstRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/res/drawable/background_community_write_view_tpye1.xml
  app/src/main/res/layout/activity_community_write.xml
Labels: 🐛bug fix

#84 가계부(Budget) : 리스트,컨탠츠(수정,추가) 기능 구현
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/data/dao/BudgetDao.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/BudgetRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/room/BudgetDatabase.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/BudgetRepository.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/CategoryAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/SwipeHelper.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetContentViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetContentViewModelFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetViewModelFactory.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/layout/activity_budget_content.xml
  app/src/main/res/layout/item_category.xml
  settings.gradle.kts
Labels: ⚙️ feat

#87 커뮤니티: 메인 -> 디테일 페이지 연결
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/res/drawable/emptycommu.png
  app/src/main/res/drawable/fbcommu.png
  app/src/main/res/drawable/usercicrlelight.png
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_main_item.xml
Labels: ⚙️ feat

#89 내정보 페이지 : 기능 수정/보완
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/GetFirebaseDatabaseRemoteSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseScrapRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/home/HomeFirstRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseScrapMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/ScrapEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ScrapMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseScrapRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseScrapData.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFirstAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/MainActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/MainTabs.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/TabLayoutListener.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/ViewPager2Adapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/FirstViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/MyPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/MyPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/res/drawable/mypage_baseline_create_24.xml
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_mypage_bookmark_item.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat

#92 좋아요 횟수 누적 이슈 해결
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/res/drawable/hollowstar.png
  app/src/main/res/drawable/imageadd.png
  app/src/main/res/drawable/paintedstar.png
  app/src/main/res/drawable/plus.png
  app/src/main/res/drawable/writepost.png
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_main_item.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: ⚙️ feat, 🐛bug fix

#95 가계부과정(Budget_Proceduere) : 디테일,컨탠츠(수정,추가) 기능 구현
  app/src/main/java/kr/sparta/tripmate/data/repository/BudgetRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/BudgetRepository.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/ProcedureContentViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/ProcedureContentViewModelFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/ProcedureDetailViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/ProcedureDetailViewModelFactory.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/layout/activity_procedure_content.xml
  app/src/main/res/layout/activity_procedure_detail.xml
  app/src/main/res/layout/itme_spinner.xml
Labels: ⚙️ feat

#97 community : UI&북마크&좋아요&VIEWS 기능 구현
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityMyModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapViewModel.kt
Labels: ⚙️ feat, ♻️refactor, 🎨design

#98 커뮤니티 : 이미지 업로드시 뷰가 사라지지않던 문제수정,디테일페이지 UI 수정
  app/src/main/res/layout/activity_community_detail.xml
Labels: ⚙️ feat, 🐛bug fix, 🎨design

#99 가계부 상세페이지 : UI 구현
  .github/workflows/Test.yml
  app/src/main/java/kr/sparta/tripmate/data/datasource/local/BudgetLocalDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/GetFirebaseDatabaseRemoteSource.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/scrap/ScrapMapper.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetDetailProcedureFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/main/BudgetDetailTab.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/main/BudgetDetailViewPagerAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/procedure/BudgetDetailProcedureListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/procedure/ProcedureModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/statistics/BudgetDetailStatisticsFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/procedure/BudgetProcedureFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/procedure/BudgetProcedureViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/drawable/selector_budget_detail_tab.xml
  app/src/main/res/drawable/shape_budget_detail_tab_bg.xml
  app/src/main/res/drawable/shape_budget_detail_tab_selected.xml
  app/src/main/res/layout/activity_budget_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_budget_detail_procedure.xml
  app/src/main/res/layout/fragment_budget_detail_statistics.xml
  app/src/main/res/layout/item_procedure.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 🎨design

#103 Community : 비지니스로직 분리
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/community/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/data/model/community/KeyModel.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseCommunityRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/CommunityModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseCommunityMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseKeyMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/KeyModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseCommunityRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseCommunityData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/IsLikeFirebaseCommunityData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/IsViewsFirebaseCommunityData.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/paintedheart.png
  app/src/main/res/drawable/usercicrlelight.png
  app/src/main/res/drawable/witness.png
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_community_main_item.xml
Labels: ⚙️ feat, 🎨design

#105 Community : 북마크 관련 로직 분리
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/community/BoardKeyModel.kt
  app/src/main/java/kr/sparta/tripmate/data/model/community/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseCommunityRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/BoardKeyModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/CommunityModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseBoardKeyMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseCommunityMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseCommunityRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseCommunityData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/UpdateCommuBoard.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
Labels: ⚙️ feat

#111 MyPage에서 북마크된 Scrap데이터 추가&삭제 시 갱신됩니다.
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeScrapListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTabLayoutAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_first_items.xml
Labels: ⚙️ feat

#113 MyPage : RDB데이터 앱에 표시& 실시간 갱신
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/GetFirebaseBoardData.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/home/MyPageTabLayoutAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardViewModel.kt
Labels: ⚙️ feat

#117 MyPage & Community UI
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
Labels: 🎨design

#118 Home : 커뮤니티 RDB데이터 화면에 표시
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
Labels: ⚙️ feat

#119 UserProfile페이지 : 페이지 구현완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/board/UserProfileBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileTab.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/main/UserProfileTabLayoutAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/userprofile/model/UserProfileModel.kt
  app/src/main/res/drawable/arrow_left_white.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/layout/fragment_user_profile_board.xml
  app/src/main/res/layout/item_user_profile_board.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🎨design

#121 로그인: 페이스북 로그인 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: ⚙️ feat

#123 Home : write& detail페이지 UI변경
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_mypage_board_item.xml
Labels: 🎨design

#125 Home& MyPage 에서 아이템을 클릭 시 동일하게 조회수가 1씩 오르게 적용했습니다.
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/IsViewsFirebaseBoardData.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardViewModel.kt
Labels: ⚙️ feat, 🐛bug fix

#127 로그인: 페이스북 롤백
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: 🐛bug fix

#131 Hotfix/budget
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/sparta/tripmate/data/repository/BudgetRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/BudgetRepository.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetContentActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/BudgetFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/BudgetContentViewModel.kt
Labels: ⚙️ feat, 🐛bug fix

#132 MyPage : 블로그 북마크 + 커뮤니티 북마크를 스크랩탭에 모두 표시하기
  app/src/main/java/kr/sparta/tripmate/api/Constants.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/model/community/CommunityModel.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseBoardRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseCommunityRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseScrapRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/CommunityModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseBookMarkMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseCommunityMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/ScrapEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseBoardRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseCommunityRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseScrapRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/GetFirebaseBoardDataFromBoardRepo.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebaseboardrepository/UpdateCommuIsViewFromBoardRepo.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/UpdateCommuBoardKey.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/UpdateCommuIsLike.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/UpdateCommuIsViewFromCommuRepo.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/UpdateCommunityBaseData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/GetFirebaseBoardDataFromScrapRepo.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/GetFirebaseScrapData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/RemoveFirebaseScrapData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/SaveFirebaseScrapData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/UpdateCommuIsViewFromScrapRepo.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/scrap/HomeScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/ScrapInterface.kt
Labels: ⚙️ feat, 📚docs

#134 Home UI변경
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeScrapListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/main/ViewPager2Adapter.kt
  app/src/main/res/drawable/homemove.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_scrap.xml
  app/src/main/res/layout/home_gridview_items.xml
  app/src/main/res/values/strings.xml
Labels: 🎨design

#136 스크랩 목록의 RDB데이터 북마크 추가&갱신
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseScrapRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseScrapRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasescraprepository/GetFirebaseBoardKeyDataFromScrapRepo.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageViewModel.kt
Labels: ⚙️ feat

#142 커뮤니티페이지 : 1차기능구현 완료
  app/build.gradle.kts
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseStorageRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseCommunityRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/data/repository/FirebaseStorageRepositoryImpl.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/CommunityModelEntity.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseBookMarkMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/model/firebase/FirebaseCommunityMapper.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseCommunityRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/repository/FirebaseStorageRepository.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/GetCommunityKeyUseCase.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasecommunityrepository/UpdateCommunityWriteData.kt
  app/src/main/java/kr/sparta/tripmate/domain/usecase/firebasestorage/UploadImageForFirebaseStorage.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityWriteActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeBoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/board/BoardListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/CommunityBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/write/CommunityWriteViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/drawable/writepost.png
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_community_write.xml
  app/src/main/res/layout/fragment_community_main_item.xml
  app/src/main/res/layout/home_gridview_items.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ⚙️ feat, 🐛bug fix, ♻️refactor, 🎨design

#149 블로그관련 북마크 아이템 삭제
  app/src/main/java/kr/sparta/tripmate/data/datasource/remote/FirebaseDBRemoteDataSource.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/main/CommunityListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapDetailFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/scrap/ScrapDetailViewModel.kt
  app/src/main/res/drawable/delete.png
  app/src/main/res/layout/activity_scrap_detail.xml
Labels: ⚙️ feat, 🐛bug fix, 🎨design

#151 Home& mypage : 조회수 증가
  app/src/main/java/kr/sparta/tripmate/ui/home/HomeFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/mypage/scrap/BookmarkFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/home/board/HomeBoardViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageFactory.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/mypage/BookmarkPageViewModel.kt
Labels: ⚙️ feat

#155 중간발표전 프로젝트 전체정리
  app/src/main/java/kr/sparta/tripmate/ui/budget/ProcedureDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/procedure/BudgetDetailProcedureFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/budget/detail/procedure/BudgetDetailProcedureListAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/community/CommunityDetailActivity.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapAdapter.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapDetail.kt
  app/src/main/java/kr/sparta/tripmate/ui/scrap/ScrapFragment.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/budget/detail/procedure/BudgetProcedureViewModel.kt
  app/src/main/java/kr/sparta/tripmate/ui/viewmodel/community/main/CommunityViewModel.kt
  app/src/main/java/kr/sparta/tripmate/util/method/method.kt
  app/src/main/res/drawable/ic_star.png
  app/src/main/res/drawable/ic_star_filled.png
  app/src/main/res/layout/activity_community_detail.xml
  app/src/main/res/layout/activity_scrap_detail.xml
  app/src/main/res/layout/fragment_budget_detail_procedure.xml
  app/src/main/res/layout/scraptitems.xml
Labels: ⚙️ feat, 💥hotfix
